### ISSUE TITLE
More than Five Options Omits Letter

### ISSUE THREAD

**Issue by a-posadas** [savsofts/savsoftquiz_v4.0_advance#6]
On default theme, if a question has more than five options, the sixth option omits the letter. 

https://imgur.com/a/BekWxpk
![image](https://user-images.githubusercontent.com/17486667/57979549-f7e51280-79e4-11e9-8ce8-2da371958389.png)

**Comment by a-posadas** [comment]
ok, it seems there is a typo on application/views/quiz_attempt_Default.php. Look for the declaration of $abc array and see that from E to F the array index goes from 4 to 6 skipping 5.

This issue can be closed.

**Comment by savsofts** [comment]
Hi,

Savsoft Quiz v5.0 has been released on GitHub.
Please try updated version

**Comment by a-posadas** [comment]
Thanks for the info. I will try it.

**Comment by a-posadas** [comment]
Same issue on version 5 but like I said, it's a typo. Easy to fix.

**Comment by a-posadas** [comment]
While I'm here I may as well mention the file application/views/setting.php should be named application/views/Setting.php with a capital "S" to work on linux.
